name: scrumlab_cpfcnpj
description: An easy-to-use utility for CPF/CNPJ validation and formatting.
version: 2.0.3
homepage: https://github.com/scrum-lab/scrumlab-dart-cpfcnpj

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.20.0"

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
